-- MySQL Script generated by MySQL Workbench
-- Sat May  7 17:26:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- drop table logging

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema words
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `words` ;

-- -----------------------------------------------------
-- Schema words
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `words` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `words` ;

-- -----------------------------------------------------
-- Table `words`.`ch_words`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `words`.`ch_words` (
  `ch_w_id` INT NOT NULL AUTO_INCREMENT,
  `word_ch` VARCHAR(500) NOT NULL,
  `word_trad` VARCHAR(500) NULL DEFAULT NULL,
  `pinyin` VARCHAR(100) NULL DEFAULT NULL,
  `Rank_Word` INT NULL DEFAULT NULL,
  `HSK` INT NULL DEFAULT NULL,
  `freq` FLOAT NULL DEFAULT NULL,
  `transl_ru` TEXT NULL DEFAULT NULL,
  `transl_eng` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ch_w_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `words`.`texts_from_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `words`.`texts_from_users` (
  `tx_from_u` INT NOT NULL AUTO_INCREMENT,
  `text_full` TEXT NOT NULL,
  `user_uploded` INT NULL,
  `uploaded_by_admin` TINYINT(1) NULL,
  PRIMARY KEY (`tx_from_u`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `words`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `words`.`user` (
  `tg_user_id` INT NOT NULL,
  `user_name` VARCHAR(100) NOT NULL,
  `lang_goal` INT NULL DEFAULT NULL,
  `join_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`tg_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `words`.`logging`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `words`.`logging` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `log_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `text_id` INT,
  `user_tg_user_id` INT NOT NULL,
  PRIMARY KEY (`log_id`),
  INDEX `fk_logging_user1_idx` (`user_tg_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_logging_user1`
    FOREIGN KEY (`user_tg_user_id`)
    REFERENCES `words`.`user` (`tg_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)-- MySQL Script generated by MySQL Workbench
    -- Sat May  7 17:26:29 2022
    -- Model: New Model    Version: 1.0
    -- MySQL Workbench Forward Engineering
    
    -- drop table logging
    
    SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
    SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
    SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
    
    -- -----------------------------------------------------
    -- Schema mydb
    -- -----------------------------------------------------
    -- -----------------------------------------------------
    -- Schema words
    -- -----------------------------------------------------
    DROP SCHEMA IF EXISTS `words` ;
    
    -- -----------------------------------------------------
    -- Schema words
    -- -----------------------------------------------------
    CREATE SCHEMA IF NOT EXISTS `words` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
    USE `words` ;
    
    -- -----------------------------------------------------
    -- Table `words`.`ch_words`
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `words`.`ch_words` (
      `ch_w_id` INT NOT NULL AUTO_INCREMENT,
      `word_ch` VARCHAR(500) NOT NULL,
      `word_trad` VARCHAR(500) NULL DEFAULT NULL,
      `pinyin` VARCHAR(100) NULL DEFAULT NULL,
      `Rank_Word` INT NULL DEFAULT NULL,
      `HSK` INT NULL DEFAULT NULL,
      `freq` FLOAT NULL DEFAULT NULL,
      `transl_ru` TEXT NULL DEFAULT NULL,
      `transl_eng` TEXT NULL DEFAULT NULL,
      PRIMARY KEY (`ch_w_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;
    
    
    -- -----------------------------------------------------
    -- Table `words`.`texts_from_users`
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `words`.`texts_from_users` (
      `tx_from_u` INT NOT NULL AUTO_INCREMENT,
      `text_full` TEXT NOT NULL,
      `user_uploded` INT NULL,
      `uploaded_by_admin` TINYINT(1) NULL,
      PRIMARY KEY (`tx_from_u`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;
    
    
    -- -----------------------------------------------------
    -- Table `words`.`user`
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `words`.`user` (
      `tg_user_id` INT NOT NULL,
      `user_name` VARCHAR(100) NOT NULL,
      `lang_goal` INT NULL DEFAULT NULL,
      `join_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (`tg_user_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;
    
    
    -- -----------------------------------------------------
    -- Table `words`.`logging`
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `words`.`logging` (
      `log_id` INT NOT NULL AUTO_INCREMENT,
      `log_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
      `text_id` INT,
      `user_tg_user_id` INT NOT NULL,
      PRIMARY KEY (`log_id`),
      INDEX `fk_logging_user1_idx` (`user_tg_user_id` ASC) VISIBLE,
      CONSTRAINT `fk_logging_user1`
        FOREIGN KEY (`user_tg_user_id`)
        REFERENCES `words`.`user` (`tg_user_id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;
    
    
    -- -----------------------------------------------------
    -- Table `words`.`texts_from_users_has_ch_words`
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `words`.`texts_from_users_has_ch_words` (
      `texts_from_users_tx_from_u` INT NOT NULL,
      `ch_words_ch_w_id` INT NOT NULL,
      PRIMARY KEY (`texts_from_users_tx_from_u`, `ch_words_ch_w_id`),
      INDEX `fk_texts_from_users_has_ch_words_ch_words1_idx` (`ch_words_ch_w_id` ASC) VISIBLE,
      INDEX `fk_texts_from_users_has_ch_words_texts_from_users1_idx` (`texts_from_users_tx_from_u` ASC) VISIBLE,
      CONSTRAINT `fk_texts_from_users_has_ch_words_texts_from_users1`
        FOREIGN KEY (`texts_from_users_tx_from_u`)
        REFERENCES `words`.`texts_from_users` (`tx_from_u`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
      CONSTRAINT `fk_texts_from_users_has_ch_words_ch_words1`
        FOREIGN KEY (`ch_words_ch_w_id`)
        REFERENCES `words`.`ch_words` (`ch_w_id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;
    
    
    -- -----------------------------------------------------
    -- Table `words`.`logging_has_texts_from_users`
    -- -----------------------------------------------------
    CREATE TABLE IF NOT EXISTS `words`.`logging_has_texts_from_users` (
      `logging_log_id` INT NOT NULL,
      `texts_from_users_tx_from_u` INT NOT NULL,
      PRIMARY KEY (`logging_log_id`, `texts_from_users_tx_from_u`),
      INDEX `fk_logging_has_texts_from_users_texts_from_users1_idx` (`texts_from_users_tx_from_u` ASC) VISIBLE,
      INDEX `fk_logging_has_texts_from_users_logging1_idx` (`logging_log_id` ASC) VISIBLE,
      CONSTRAINT `fk_logging_has_texts_from_users_logging1`
        FOREIGN KEY (`logging_log_id`)
        REFERENCES `words`.`logging` (`log_id`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
      CONSTRAINT `fk_logging_has_texts_from_users_texts_from_users1`
        FOREIGN KEY (`texts_from_users_tx_from_u`)
        REFERENCES `words`.`texts_from_users` (`tx_from_u`)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;
    
    
    SET SQL_MODE=@OLD_SQL_MODE;
    SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
    SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `words`.`texts_from_users_has_ch_words`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `words`.`texts_from_users_has_ch_words` (
  `texts_from_users_tx_from_u` INT NOT NULL,
  `ch_words_ch_w_id` INT NOT NULL,
  PRIMARY KEY (`texts_from_users_tx_from_u`, `ch_words_ch_w_id`),
  INDEX `fk_texts_from_users_has_ch_words_ch_words1_idx` (`ch_words_ch_w_id` ASC) VISIBLE,
  INDEX `fk_texts_from_users_has_ch_words_texts_from_users1_idx` (`texts_from_users_tx_from_u` ASC) VISIBLE,
  CONSTRAINT `fk_texts_from_users_has_ch_words_texts_from_users1`
    FOREIGN KEY (`texts_from_users_tx_from_u`)
    REFERENCES `words`.`texts_from_users` (`tx_from_u`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_texts_from_users_has_ch_words_ch_words1`
    FOREIGN KEY (`ch_words_ch_w_id`)
    REFERENCES `words`.`ch_words` (`ch_w_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `words`.`logging_has_texts_from_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `words`.`logging_has_texts_from_users` (
  `logging_log_id` INT NOT NULL,
  `texts_from_users_tx_from_u` INT NOT NULL,
  PRIMARY KEY (`logging_log_id`, `texts_from_users_tx_from_u`),
  INDEX `fk_logging_has_texts_from_users_texts_from_users1_idx` (`texts_from_users_tx_from_u` ASC) VISIBLE,
  INDEX `fk_logging_has_texts_from_users_logging1_idx` (`logging_log_id` ASC) VISIBLE,
  CONSTRAINT `fk_logging_has_texts_from_users_logging1`
    FOREIGN KEY (`logging_log_id`)
    REFERENCES `words`.`logging` (`log_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logging_has_texts_from_users_texts_from_users1`
    FOREIGN KEY (`texts_from_users_tx_from_u`)
    REFERENCES `words`.`texts_from_users` (`tx_from_u`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
