-- MySQL Script generated by MySQL Workbench
-- Sat May 28 17:15:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema words
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema words
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `words` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `words` ;

-- -----------------------------------------------------
-- Table `words`.`admin_texts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words`.`admin_texts` ;

CREATE TABLE IF NOT EXISTS `words`.`admin_texts` (
  `admin_text_id` INT NOT NULL AUTO_INCREMENT,
  `text_full` TEXT NOT NULL,
  `hsk` INT NOT NULL,
  `title` VARCHAR(1000) NULL DEFAULT NULL,
  `url` VARCHAR(1000) NULL DEFAULT NULL,
  `title_eng` VARCHAR(400) NULL DEFAULT NULL,
  `dateAdded` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`admin_text_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1309
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `words`.`logging`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words`.`logging` ;

CREATE TABLE IF NOT EXISTS `words`.`logging` (
  `log_id` INT NOT NULL AUTO_INCREMENT,
  `log_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `text_id` INT NULL DEFAULT NULL,
  `user_tg_user_id` INT NOT NULL,
  `action` VARCHAR(100) NULL DEFAULT NULL,
  `text` VARCHAR(300) NULL DEFAULT NULL,
  `admin_text` TINYINT NULL DEFAULT '0',
  PRIMARY KEY (`log_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 170
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `words`.`admin_texts_has_logging`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words`.`admin_texts_has_logging` ;

CREATE TABLE IF NOT EXISTS `words`.`admin_texts_has_logging` (
  `admin_texts_admin_text_id` INT NOT NULL,
  `logging_log_id` INT NOT NULL,
  PRIMARY KEY (`admin_texts_admin_text_id`, `logging_log_id`),
  INDEX `fk_admin_texts_has_logging_logging1_idx` (`logging_log_id` ASC) VISIBLE,
  INDEX `fk_admin_texts_has_logging_admin_texts1_idx` (`admin_texts_admin_text_id` ASC) VISIBLE,
  CONSTRAINT `fk_admin_texts_has_logging_admin_texts1`
    FOREIGN KEY (`admin_texts_admin_text_id`)
    REFERENCES `words`.`admin_texts` (`admin_text_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_texts_has_logging_logging1`
    FOREIGN KEY (`logging_log_id`)
    REFERENCES `words`.`logging` (`log_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `words`.`ch_words`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words`.`ch_words` ;

CREATE TABLE IF NOT EXISTS `words`.`ch_words` (
  `ch_w_id` INT NOT NULL AUTO_INCREMENT,
  `word_ch` VARCHAR(500) NOT NULL,
  `word_trad` VARCHAR(500) NULL DEFAULT NULL,
  `pinyin` VARCHAR(100) NULL DEFAULT NULL,
  `Rank_Word` INT NULL DEFAULT NULL,
  `HSK` INT NULL DEFAULT NULL,
  `freq` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`ch_w_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 84946
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `words`.`eng`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words`.`eng` ;

CREATE TABLE IF NOT EXISTS `words`.`eng` (
  `eng_id` INT NOT NULL AUTO_INCREMENT,
  `translation` VARCHAR(500) NOT NULL,
  `chinese` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`eng_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 510129
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `words`.`ch_eng`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words`.`ch_eng` ;

CREATE TABLE IF NOT EXISTS `words`.`ch_eng` (
  `ch_id` INT NOT NULL,
  `eng_id` INT NULL DEFAULT NULL,
  INDEX `ch_id_idx` (`ch_id` ASC) VISIBLE,
  INDEX `eng_id_idx` (`eng_id` ASC) VISIBLE,
  CONSTRAINT `ch_id`
    FOREIGN KEY (`ch_id`)
    REFERENCES `words`.`ch_words` (`ch_w_id`)
    ON UPDATE CASCADE,
  CONSTRAINT `eng_id`
    FOREIGN KEY (`eng_id`)
    REFERENCES `words`.`eng` (`eng_id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `words`.`ch_words_has_admin_texts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words`.`ch_words_has_admin_texts` ;

CREATE TABLE IF NOT EXISTS `words`.`ch_words_has_admin_texts` (
  `ch_words_ch_w_id` INT NOT NULL,
  `admin_texts_admin_text_id` INT NOT NULL,
  PRIMARY KEY (`ch_words_ch_w_id`, `admin_texts_admin_text_id`),
  INDEX `fk_ch_words_has_admin_texts_admin_texts1_idx` (`admin_texts_admin_text_id` ASC) VISIBLE,
  INDEX `fk_ch_words_has_admin_texts_ch_words1_idx` (`ch_words_ch_w_id` ASC) VISIBLE,
  CONSTRAINT `fk_ch_words_has_admin_texts_admin_texts1`
    FOREIGN KEY (`admin_texts_admin_text_id`)
    REFERENCES `words`.`admin_texts` (`admin_text_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ch_words_has_admin_texts_ch_words1`
    FOREIGN KEY (`ch_words_ch_w_id`)
    REFERENCES `words`.`ch_words` (`ch_w_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `words`.`texts_from_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words`.`texts_from_users` ;

CREATE TABLE IF NOT EXISTS `words`.`texts_from_users` (
  `tx_from_u` INT NOT NULL AUTO_INCREMENT,
  `text_full` TEXT NOT NULL,
  `uploaded_by_admin` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`tx_from_u`))
ENGINE = InnoDB
AUTO_INCREMENT = 103
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `words`.`ch_words_has_texts_from_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words`.`ch_words_has_texts_from_users` ;

CREATE TABLE IF NOT EXISTS `words`.`ch_words_has_texts_from_users` (
  `ch_words_ch_w_id` INT NOT NULL,
  `texts_from_users_tx_from_u` INT NOT NULL,
  INDEX `fk_ch_words_has_texts_from_users_texts_from_users1_idx` (`texts_from_users_tx_from_u` ASC) VISIBLE,
  INDEX `fk_ch_words_has_texts_from_users_ch_words1_idx` (`ch_words_ch_w_id` ASC) VISIBLE,
  CONSTRAINT `fk_ch_words_has_texts_from_users_ch_words1`
    FOREIGN KEY (`ch_words_ch_w_id`)
    REFERENCES `words`.`ch_words` (`ch_w_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ch_words_has_texts_from_users_texts_from_users1`
    FOREIGN KEY (`texts_from_users_tx_from_u`)
    REFERENCES `words`.`texts_from_users` (`tx_from_u`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `words`.`logging_has_texts_from_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words`.`logging_has_texts_from_users` ;

CREATE TABLE IF NOT EXISTS `words`.`logging_has_texts_from_users` (
  `logging_log_id` INT NOT NULL,
  `texts_from_users_tx_from_u` INT NOT NULL,
  PRIMARY KEY (`logging_log_id`, `texts_from_users_tx_from_u`),
  INDEX `fk_logging_has_texts_from_users_texts_from_users1_idx` (`texts_from_users_tx_from_u` ASC) VISIBLE,
  INDEX `fk_logging_has_texts_from_users_logging1_idx` (`logging_log_id` ASC) VISIBLE,
  CONSTRAINT `fk_logging_has_texts_from_users_logging1`
    FOREIGN KEY (`logging_log_id`)
    REFERENCES `words`.`logging` (`log_id`),
  CONSTRAINT `fk_logging_has_texts_from_users_texts_from_users1`
    FOREIGN KEY (`texts_from_users_tx_from_u`)
    REFERENCES `words`.`texts_from_users` (`tx_from_u`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `words`.`unique_words`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words`.`unique_words` ;

CREATE TABLE IF NOT EXISTS `words`.`unique_words` (
  `ch_words_ch_w_id` INT NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT 'Know',
  PRIMARY KEY (`ch_words_ch_w_id`),
  INDEX `fk_logging_has_texts_from_users_copy1_ch_words1_idx` (`ch_words_ch_w_id` ASC) VISIBLE,
  CONSTRAINT `fk_logging_has_texts_from_users_copy1_ch_words1`
    FOREIGN KEY (`ch_words_ch_w_id`)
    REFERENCES `words`.`ch_words` (`ch_w_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `words`.`unknown_words`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words`.`unknown_words` ;

CREATE TABLE IF NOT EXISTS `words`.`unknown_words` (
  `words` VARCHAR(100) NOT NULL,
  `unk_id` INT NOT NULL,
  `logging_log_id` INT NOT NULL,
  PRIMARY KEY (`unk_id`),
  INDEX `fk_unknown_words_logging1_idx` (`logging_log_id` ASC) VISIBLE,
  CONSTRAINT `fk_unknown_words_logging1`
    FOREIGN KEY (`logging_log_id`)
    REFERENCES `words`.`logging` (`log_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `words`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `words`.`user` ;

CREATE TABLE IF NOT EXISTS `words`.`user` (
  `tg_user_id` INT NOT NULL,
  `user_name` VARCHAR(100) NOT NULL,
  `lang_goal` INT NULL DEFAULT NULL,
  `join_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`tg_user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
